[tool.poetry]
name = "pyrepr"
version = "0.1.1"
description = ""
authors = ["patarapolw <patarapolw@gmail.com>"]

[tool.poetry.dependencies]
python = "*"
prettyprinter = "^0.14.0"

[tool.poetry.dev-dependencies]
